import flet as ft
from flet import (
    Card, Container, Text, Image, Row, Column, ListView,
    Colors, Padding, BorderRadius, FontWeight, MainAxisAlignment,
    CrossAxisAlignment, BoxFit,
)
from app.config import STATUS_LOOKUP

TRANSLATIONS = {
    "en": {
        "app_title": "Farm Tree Manager",
        "nav_trees": "Trees",
        "nav_add": "Add",
        "nav_settings": "Settings",
        "search_hint": "Search trees... (use | for AND)",
        "search": "Search",
        "refresh": "Refresh",
        "statistics": "Statistics",
        "add_new_tree": "Add New Tree",
        "tree_details": "Tree Details",
        "photo": "Photo",
        "location": "Location",
        "take_photo": "Take Photo",
        "no_photo": "No photo captured",
        "sector": "Sector",
        "zone": "Zone",
        "row": "Row",
        "tree": "Tree",
        "tree_code": "Tree Code",
        "tree_code_hint": "Auto-generated from Sector/Zone/Row/Tree#",
        "kind": "Kind",
        "kind_required": "Kind *",
        "variety": "Variety",
        "variety_hint": "Select variety",
        "status": "Status",
        "status_required": "Status *",
        "notes": "Notes",
        "save_tree": "Save Tree",
        "save_next": "Save & Next",
        "edit_tree": "Edit Tree",
        "visit_history": "Visit History",
        "add_new_visit": "Add New Visit",
        "visit_status": "Visit Status *",
        "visit_notes": "Visit Notes",
        "visit_photos": "Visit Photos",
        "add_photos": "Add Photos",
        "save_changes": "Save Changes",
        "delete_tree": "Delete Tree",
        "edit": "Edit",
        "new_visit": "New Visit",
        "delete": "Delete",
        "cancel": "Cancel",
        "close": "Close",
        "yes": "Yes",
        "no": "No",
        "settings": "Settings",
        "help": "Help",
        "help_subtitle": "Learn how to use the app",
        "about": "About",
        "about_subtitle": "Farm Tree Manager v",
        "view_logs": "View Logs",
        "view_logs_subtitle": "Check app logs for troubleshooting",
        "language": "Language",
        "language_subtitle": "Change app language",
        "total_trees": "Total Trees: ",
        "searched_trees": "Searched Trees: ",
        "heatmap_title": "Tree Density Heatmap",
        "barchart_title": "Trees per Sector",
        "no_tree_available": "No Tree Available",
        "no_trees_found": "No trees found",
        "tap_to_add": "Tap + to add your first tree",
        "loading": "Loading trees...",
        "loading_sub": "Please wait while we gather your data",
        "page": "Page ",
        "back": "Back",
        "help_title": "Help",
        "help_text_1": "Tap + to add a new tree.",
        "help_text_2": "Tap a tree card to view its details.",
        "help_text_3": "Long-press a tree for quick actions.",
        "help_text_4": "Use the search bar to find trees.",
        "help_text_5": "Track visits and update tree status.",
        "help_text_6": "Photos and notes can be added per visit.",
        "about_title": "About",
        "about_desc": "A farm tree management app for tracking tree health, visits, and maintenance.",
        "logs_title": "Logs",
        "confirm_delete": "Are you sure you want to delete this tree and all its visits?",
        "delete_title": "Delete Tree",
        "actions": "Actions",
        "edit_action": "Edit Tree",
        "quick_status": "Quick Status Change",
        "view_history": "View History",
        "delete_action": "Delete Tree",
        "change_status": "Change Status",
        "gps_getting": "Getting GPS location...",
        "gps_captured": "GPS coordinates captured",
        "gps_unavailable": "GPS location unavailable",
        "camera_not_available": "Camera not available on this platform",
        "photo_captured": "Photo captured!",
        "camera_error": "Camera error: ",
        "tree_added": "Tree added successfully!",
        "tree_added_next": "Tree added! Ready for next.",
        "tree_updated": "Tree updated successfully!",
        "tree_deleted": "Tree deleted",
        "error_saving": "Error saving tree",
        "error_updating": "Error updating tree",
        "error_deleting": "Error deleting tree",
        "error_loading": "Error loading trees",
        "error_stats": "Error loading statistics",
        "tree_code_required": "Tree code is required",
        "kind_required_msg": "Kind is required",
        "status_required_msg": "Status is required",
        "sector_positive": "Sector must be a positive number",
        "zone_positive": "Zone must be a positive number",
        "row_positive": "Row must be a positive number",
        "tree_positive": "Tree must be a positive number",
        "error_saving_photo": "Error saving photo",
    },
    "ar": {
        "app_title": "مدير أشجار المزرعة",
        "nav_trees": "الأشجار",
        "nav_add": "إضافة",
        "nav_settings": "الإعدادات",
        "search_hint": "بحث في الأشجار... (استخدم | لـ و)",
        "search": "بحث",
        "refresh": "تحديث",
        "statistics": "الإحصائيات",
        "add_new_tree": "إضافة شجرة جديدة",
        "tree_details": "تفاصيل الشجرة",
        "photo": "الصورة",
        "location": "الموقع",
        "take_photo": "التقاط صورة",
        "no_photo": "لم يتم التقاط صورة",
        "sector": "القطاع",
        "zone": "المنطقة",
        "row": "الصف",
        "tree": "الشجرة",
        "tree_code": "رمز الشجرة",
        "tree_code_hint": "يُولّد تلقائياً من القطاع/المنطقة/الصف/رقم الشجرة",
        "kind": "النوع",
        "kind_required": "النوع *",
        "variety": "الصنف",
        "variety_hint": "اختر الصنف",
        "status": "الحالة",
        "status_required": "الحالة *",
        "notes": "ملاحظات",
        "save_tree": "حفظ الشجرة",
        "save_next": "حفظ والتالي",
        "edit_tree": "تعديل الشجرة",
        "visit_history": "سجل الزيارات",
        "add_new_visit": "إضافة زيارة جديدة",
        "visit_status": "حالة الزيارة *",
        "visit_notes": "ملاحظات الزيارة",
        "visit_photos": "صور الزيارة",
        "add_photos": "إضافة صور",
        "save_changes": "حفظ التغييرات",
        "delete_tree": "حذف الشجرة",
        "edit": "تعديل",
        "new_visit": "زيارة جديدة",
        "delete": "حذف",
        "cancel": "إلغاء",
        "close": "إغلاق",
        "yes": "نعم",
        "no": "لا",
        "settings": "الإعدادات",
        "help": "المساعدة",
        "help_subtitle": "تعرف على كيفية استخدام التطبيق",
        "about": "حول",
        "about_subtitle": "مدير أشجار المزرعة v",
        "view_logs": "عرض السجلات",
        "view_logs_subtitle": "تحقق من سجلات التطبيق لحل المشكلات",
        "language": "اللغة",
        "language_subtitle": "تغيير لغة التطبيق",
        "total_trees": "إجمالي الأشجار: ",
        "searched_trees": "الأشجار المُبحث عنها: ",
        "heatmap_title": "خريطة كثافة الأشجار",
        "barchart_title": "الأشجار حسب القطاع",
        "no_tree_available": "لا توجد أشجار متاحة",
        "no_trees_found": "لم يتم العثور على أشجار",
        "tap_to_add": "اضغط + لإضافة أول شجرة",
        "loading": "جاري تحميل الأشجار...",
        "loading_sub": "يرجى الانتظار حتى نجمع بياناتك",
        "page": "صفحة ",
        "back": "رجوع",
        "help_title": "المساعدة",
        "help_text_1": "اضغط + لإضافة شجرة جديدة.",
        "help_text_2": "اضغط على بطاقة الشجرة لعرض تفاصيلها.",
        "help_text_3": "اضغط مطولاً على شجرة للإجراءات السريعة.",
        "help_text_4": "استخدم شريط البحث للعثور على الأشجار.",
        "help_text_5": "تتبع الزيارات وحدّح حالة الشجرة.",
        "help_text_6": "يمكن إضافة صور وملاحظات لكل زيارة.",
        "about_title": "حول",
        "about_desc": "تطبيق إدارة أشجار المزرعة لتتبع صحة الأشجار والزيارات والصيانة.",
        "logs_title": "السجلات",
        "confirm_delete": "هل أنت متأكد أنك تريد حذف هذه الشجرة وجميع زياراتها؟",
        "delete_title": "حذف الشجرة",
        "actions": "الإجراءات",
        "edit_action": "تعديل الشجرة",
        "quick_status": "تغيير سريع للحالة",
        "view_history": "عرض السجل",
        "delete_action": "حذف الشجرة",
        "change_status": "تغيير الحالة",
        "gps_getting": "جاري الحصول على الموقع...",
        "gps_captured": "تم التقاط إحداثيات GPS",
        "gps_unavailable": "موقع GPS غير متاح",
        "camera_not_available": "الكاميرا غير متاحة على هذه المنصة",
        "photo_captured": "تم التقاط الصورة!",
        "camera_error": "خطأ في الكاميرا: ",
        "tree_added": "تمت إضافة الشجرة بنجاح!",
        "tree_added_next": "تمت الإضافة! جاهز للتالي.",
        "tree_updated": "تم تحديث الشجرة بنجاح!",
        "tree_deleted": "تم حذف الشجرة",
        "error_saving": "خطأ في حفظ الشجرة",
        "error_updating": "خطأ في تحديث الشجرة",
        "error_deleting": "خطأ في حذف الشجرة",
        "error_loading": "خطأ في تحميل الأشجار",
        "error_stats": "خطأ في تحميل الإحصائيات",
        "tree_code_required": "رمز الشجرة مطلوب",
        "kind_required_msg": "النوع مطلوب",
        "status_required_msg": "الحالة مطلوبة",
        "sector_positive": "يجب أن يكون القطاع رقماً موجباً",
        "zone_positive": "يجب أن تكون المنطقة رقماً موجباً",
        "row_positive": "يجب أن يكون الصف رقماً موجباً",
        "tree_positive": "يجب أن يكون رقم الشجرة رقماً موجباً",
        "error_saving_photo": "خطأ في حفظ الصورة",
    },
}


def build_visit_card(visit: dict, photo_size: int = 50) -> Card:
    status = visit.get("status", "")
    color = STATUS_LOOKUP.get(status, Colors.GREY)
    photos = visit.get("photos", [])
    photo_chips = [
        Container(
            content=Image(src=p, fit=BoxFit.COVER, width=photo_size, height=photo_size, border_radius=BorderRadius(6, 6, 6, 6)),
            width=photo_size, height=photo_size, border_radius=BorderRadius(6, 6, 6, 6), clip_behavior=ft.ClipBehavior.HARD_EDGE,
        ) for p in photos
    ]
    return Card(
        content=Container(
            content=Column([
                Row([
                    Text(visit.get("visit_dt", ""), weight=FontWeight.BOLD, size=13, font_family="Comfortaa"),
                    Container(
                        content=Text(status, size=11, weight=FontWeight.W_500, color=Colors.WHITE, font_family="Comfortaa"),
                        bgcolor=color, padding=Padding(6, 2, 6, 2), border_radius=BorderRadius(10, 10, 10, 10),
                    ),
                ], alignment=MainAxisAlignment.SPACE_BETWEEN),
                Text(visit.get("notes", "No notes"), size=13, color=Colors.GREY_700, font_family="Comfortaa"),
                Row(photo_chips, spacing=4) if photo_chips else Container(),
            ], spacing=4, tight=True),
            padding=Padding(12, 10, 12, 10),
        ),
        elevation=1,
    )
